# Generated by Django 5.2.8 on 2025-11-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='collaboration_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='weekly_tasks',
            field=models.TextField(blank=True),
        ),
    ]
